### ISSUE TITLE
抽老婆优化建议

### ISSUE THREAD

**Issue by HydrangeaPurple** [krau/kmua-bot#1]
我有个优化建议, 给管理员开一个清空抽老婆列表的功能, 
因为大群里有人发广告, 然后搞得经常能把广告哥哥抽出来....
![image](https://github.com/krau/kmua-bot/assets/21093249/27fe7d07-84e8-4647-b746-2da8df6da914)

好几天都是这样的

关键是这些人都被踢掉过了, 但是还能抽出来, 就算把bot移除群聊在加进来, 还是记住了这些人.
应该是bot自己记录了在群里发言的人. 
这个记录, 最好给一个能清空的方法吧.

**Comment by krau** [comment]
实际上, 被踢掉的人会从 bot 的记录中清除掉的, 以后再抽的时候就不会再抽出来被踢了的人.
但是每个人的老婆数据是独立于群组的. 是像下面这样格式存储的
```json
    "today_waifu": {
        "user_id1": {
            "chat_id1": "waifu_id1",
            "chat_id2": "waifu_id2"
        },
        "user_id2": {
            "chat_id3": "waifu_id3",
            "chat_id4": "waifu_id4"
        }
    }
```
`user_id` 就是用户 id , `chat_id` 就是群组 id, `waifu_id` 就是在群组中抽出来的老婆的 id 了. 这个数据每天 4:00 刷新.
这部分的可能有点小问题, 抽出来广告哥的倒霉蛋可以反馈给管理员把广告踢了, 其他人就不会再抽出来, 但倒霉蛋今天依旧是倒霉蛋.(
所以也不需要清空记录什么的, 给用户一个换老婆的机会好了

---
如果观察到我第一句 "以后再抽的时候就不会再抽出来被踢了的人" 与事实不符, 欢迎继续反馈

**Comment by krau** [comment]
https://github.com/krau/kmua-bot/commit/c294f2f23e28139fd111cc5801570cb2e2eafe6c
