### ISSUE TITLE
载入史册命令一直提示请回复一条消息

### ISSUE THREAD

**Issue by DancingSnow0517** [krau/kmua-bot#24]
![Screenshot_2023-11-05-09-38-37-34_948cd9899890cbd5c2798760b2b95377.jpg](https://github.com/krau/kmua-bot/assets/60736156/3d3b3f95-78e2-460c-ae74-342da9f1b17e)

不清楚是不是新版tg手机客户端导致的

**Comment by krau** [comment]
1, 由于 tg bot api 的设计缺陷, bot 无法在开启了话题的群组的非 General 话题之外使用此功能.
2. 基于 tg bot api 的 bot 只能获取你将 bot 拉入群组**之后**的消息

请你检查一下是否为上述两个原因

**Comment by DancingSnow0517** [comment]
上图可见是在bot加入后发的消息并且使用命令
以及群组并未开启话题功能
![Screenshot_2023-11-05-12-10-22-78_948cd9899890cbd5c2798760b2b95377.jpg](https://github.com/krau/kmua-bot/assets/60736156/f4f7f1da-1ee6-4185-a949-943fda09f66d)

**Comment by DancingSnow0517** [comment]
> 1, 由于 tg bot api 的设计缺陷, bot 无法在开启了话题的群组的非 General 话题之外使用此功能.
> 2. 基于 tg bot api 的 bot 只能获取你将 bot 拉入群组**之后**的消息
> 
> 请你检查一下是否为上述两个原因

检查了下，确实是1导致的问题，感谢
