### ISSUE TITLE
Cannot generate quoted pictures while using docker to deploy Kmua

### ISSUE THREAD

**Issue by RickyLottery** [krau/kmua-bot#26]
作者你好，我很喜欢这个机器人。当我使用docker按照readme里面所提供的配置部署Kmua到自己的机器上的时候，我发现在群聊里Kmua可以quote到我所引用的消息，但是并不能正常的生成图片, 请问这个问题您有没有遇到过呢？

另外，我想了解一下有没有设定可以引用的时候只让Kmua加入语录而不pin这个message呢？

期待您的回复

**Comment by krau** [comment]
1. kmua 目前只对文字消息生成图片, 并且字数大于200的消息也不生成
2. 只要在群组中不赋予kmua置顶消息的权限, 她便不会pin
