### ISSUE TITLE
自部署貌似在自我数据管理上有点问题

### ISSUE THREAD

**Issue by tjsky** [krau/kmua-bot#37]
我使用docker-从按照readme里面所提供的配置部署Kmua到自己的机器上的时候
使用/start 并不能呼出菜单
doker日志里显示为

```
2024-03-07 16:08:23.441 | INFO     | kmua.callbacks.start:start:26 - [日] <start>
2024-03-07 16:08:24.178 | ERROR    | kmua.handlers:on_error:292 - 在该更新发生错误
Update(message=Message(channel_chat_created=False, chat=Chat(first_name='日', id=63295008, type=<ChatType.PRIVATE>), date=datetime.datetime(2024, 3, 7, 16, 8, 23, tzinfo=<DstTzInfo 'Asia/Shanghai' CST+8:00:00 STD>), delete_chat_photo=False, entities=(MessageEntity(length=6, offset=0, type=<MessageEntityType.BOT_COMMAND>),), from_user=User(first_name='日', id=63295008, is_bot=False, language_code='zh-hans'), group_chat_created=False, message_id=18, supergroup_chat_created=False, text='/start'), update_id=271499)
错误信息
BadRequest:There is no photo in the request
#里面涉及的个人信息，是我按照报错格式瞎写的
```

看报错貌似其他信息都正常拉取到了，只是因为没获取到头像，导致/srart触发的回复消息没有发出来。
但是群里/q和/waifu时，bot确实获取到了头像，就有点搞不懂原因了。
已在botfather关闭隐私模式，开启内联，我之所以出错，是因为我还需要做什么额外的设置吗？

**Comment by krau** [comment]
这里应该是没有获取到bot自己的头像，你为它设置了吗？

**Comment by tjsky** [comment]
有设置的`Botpic: 🖼 has a botpic`
目前尝试过更换图片，重启docker，还是无效

**Comment by tjsky** [comment]
我修好了

研究了一下这一块儿代码的逻辑
因为我的部署步骤是：
先建立了bot，还没设置头像时，启动了bot，对bot发过了/start，然后再设置的bot头像、内联、隐私模式等。
看这一块，bot不会主动更新数据，导致一直报错。

那么解决办法，要么自己去数据库里改一下，要么直接删除数据库，重新运行bot，重新拉取头像


看来部署步骤里要强调一下：先在botfather里给bot设置好头像，内联，隐私模式关，然后再启动bot程序

**Comment by krau** [comment]
> 我修好了
> 
> 研究了一下这一块儿代码的逻辑 因为我的部署步骤是： 先建立了bot，还没设置头像时，启动了bot，对bot发过了/start，然后再设置的bot头像、内联、隐私模式等。 看这一块，bot不会主动更新数据，导致一直报错。
> 
> 那么解决办法，要么自己去数据库里改一下，要么直接删除数据库，重新运行bot，重新拉取头像
> 
> 看来部署步骤里要强调一下：先在botfather里给bot设置好头像，内联，隐私模式关，然后再启动bot程序

我自己开发时使用的bot一直是有头像的, 确实没注意到这里的问题, 感谢补充
