### ISSUE TITLE
Automatic database migration

### ISSUE THREAD

**Issue by tjsky** [krau/kmua-bot#45]
简而言之就是 [add title_perssion to ChatData](https://github.com/krau/kmua-bot/commit/12e87692bf978e9e585d167ab7a825b457409123) 给`chat_data`增加了`title_permissions`

但是如果是docker compose部署，从旧镜像（比如 [sha-82b5a8e](https://github.com/users/krau/packages/container/kmua-bot/195020173?tag=sha-82b5a8e) ），直接pull到最新版的镜像（比如[sha-25dec5b](https://github.com/users/krau/packages/container/kmua-bot/212377840?tag=sha-25dec5b)），这部分不会被正确执行。

然后就会疯狂报错
```
OperationalError:(sqlite3.OperationalError) no such column: chat_data.title_permissions
```

于是我不得不进docker手动执行了一下alembic upgrade

**Comment by krau** [comment]
实际上自动迁移并没有做，我自己也是一直用 alembic 手动的（
这个当做个改进 todo 吧

**Comment by tjsky** [comment]
> 实际上自动迁移并没有做，我自己也是一直用 alembic 手动的（ 这个当做个改进 todo 吧

难怪我翻了半天没看到自动迁移相关，还以为是自己看漏了
