### ISSUE TITLE
/ip example.com?lang=zh-CN，地区会返回中文，这是特性还是bug？

### ISSUE THREAD

**Issue by real-LiHua** [krau/kmua-bot#47]
由于正则表达式不包含`^`和`$`，且`Pattern.match`并不是将整个字符串与正则表达式匹配
`?lang=zh-CN` 通过以下限制
https://github.com/krau/kmua-bot/blob/4bc5ad907f41bc987462c6c14a7401de15fe93a0/kmua/callbacks/ip.py#L50-L52
到了下段代码中
https://github.com/krau/kmua-bot/blob/4bc5ad907f41bc987462c6c14a7401de15fe93a0/kmua/callbacks/ip.py#L66-L75
例子中 url 为 <http://ip-api.com/json/example.com?lang=zh-CN>，按照 <http://ip-api.com/docs/api:json>，结果返回中文
![图片](https://github.com/krau/kmua-bot/assets/65490624/2da5b1dc-106d-4e36-9c12-fd195fda115d)
对于 IPv4 和 IPv6 也是如此

**Comment by real-LiHua** [comment]
如果是`/ip example.com?callback=cb`，则会触发 JSONDecodeError

**Comment by krau** [comment]
没能阻止预期之外的输入，是bug

**Comment by krau** [comment]
https://github.com/krau/kmua-bot/commit/4fc927bf5e805b91610b4d7d9bada9b7786e5ea3

**Comment by a091538383** [comment]
是的！中文電腦

Krau ***@***.***> 於 2024年6月9日 週日 11:25 寫道：

**Comment by a091538383** [comment]
原文論
