### ISSUE TITLE
没有头像的话，/q 不能生成图片

### ISSUE THREAD

**Issue by laosiji888** [krau/kmua-bot#50]

**Comment by krau** [comment]
没有头像怎么生成图片

**Comment by laosiji888** [comment]
> 没有头像怎么生成图片

可以把用户名或者昵称当作图片。。。

**Comment by krau** [comment]
https://github.com/krau/kmua-bot/commit/7d46fea9fb79c05dcf6e1da67ff7bf8a985eefc4
